#define MSJ_BIENVENIDA1 "Ejercicio 24"
#define MSJ_BIENVENIDA2 "Ingrese numero de dias"
#define MSJ_ERR_RANGO "Rango incorrecto"
#define DOM "Dia Domingo"
#define LUN "Dia Lunes"
#define MAR "Dia Martes"
#define MIE "Dia Miercoles"
#define JUE "Dia Jueves"
#define VIE "Dia Viernes"
#define SAB "Dia Sabado"
