#define MSJ_KM_RECORRIDOS "Ingrese los kilometros recorridos (-1 para terminar): "
#define MSJ_$_COMBUSTIBLE "Ingrese el precio del combustible por litro: "
#define MSJ_$_TOTAL "Ingrese el monto total utilizado en este compra: "
#define MSJ_RND_TANQUE "Rendimiento (l/100km) de este tanque >> "
#define MSJ_RND_PROM "Rendimiento promedio (l/100km) >> "
#define MSJ_MAX_PROM "Mejor rendimiento (l/100km) >> "
#define MSJ_MIN_PROM "Peor rendimiento (l/100km) >> "
#define MSJ_DIST_TOT "Distancia total recorrida (km) >> "
#define MSJ_COMBUSTIBLE_TOT "Combustible total consumidos (l) >> "
#define MSJ_$_TOT "Costo total de su vehiculo ($) >> "
